import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

const militaryRankings = [
  {
    rank: 1,
    country: "États-Unis",
    flag: "🇺🇸",
    power: 98.5,
    budget: "778 Md$",
    forces: "1.4M",
  },
  {
    rank: 2,
    country: "Russie",
    flag: "🇷🇺",
    power: 94.2,
    budget: "65 Md$",
    forces: "1.0M",
  },
  {
    rank: 3,
    country: "Chine",
    flag: "🇨🇳",
    power: 92.8,
    budget: "250 Md$",
    forces: "2.0M",
  },
  {
    rank: 4,
    country: "Inde",
    flag: "🇮🇳",
    power: 89.1,
    budget: "73 Md$",
    forces: "1.4M",
  },
  {
    rank: 5,
    country: "Royaume-Uni",
    flag: "🇬🇧",
    power: 85.7,
    budget: "68 Md$",
    forces: "194K",
  },
  {
    rank: 6,
    country: "France",
    flag: "🇫🇷",
    power: 84.3,
    budget: "53 Md$",
    forces: "269K",
  },
  {
    rank: 7,
    country: "Japon",
    flag: "🇯🇵",
    power: 82.9,
    budget: "49 Md$",
    forces: "247K",
  },
  {
    rank: 8,
    country: "Corée du Sud",
    flag: "🇰🇷",
    power: 81.5,
    budget: "46 Md$",
    forces: "599K",
  },
  {
    rank: 9,
    country: "Allemagne",
    flag: "🇩🇪",
    power: 79.2,
    budget: "52 Md$",
    forces: "184K",
  },
  {
    rank: 10,
    country: "Italie",
    flag: "🇮🇹",
    power: 77.8,
    budget: "29 Md$",
    forces: "171K",
  },
  {
    rank: 11,
    country: "Turquie",
    flag: "🇹🇷",
    power: 76.4,
    budget: "17 Md$",
    forces: "355K",
  },
  {
    rank: 12,
    country: "Israël",
    flag: "🇮🇱",
    power: 75.1,
    budget: "24 Md$",
    forces: "170K",
  },
  {
    rank: 13,
    country: "Pakistan",
    flag: "🇵🇰",
    power: 74.2,
    budget: "11 Md$",
    forces: "654K",
  },
  {
    rank: 14,
    country: "Brésil",
    flag: "🇧🇷",
    power: 73.1,
    budget: "19 Md$",
    forces: "334K",
  },
  {
    rank: 15,
    country: "Iran",
    flag: "🇮🇷",
    power: 71.8,
    budget: "25 Md$",
    forces: "610K",
  },
  {
    rank: 16,
    country: "Égypte",
    flag: "🇪🇬",
    power: 70.5,
    budget: "4 Md$",
    forces: "438K",
  },
  {
    rank: 17,
    country: "Australie",
    flag: "🇦🇺",
    power: 69.3,
    budget: "27 Md$",
    forces: "59K",
  },
  {
    rank: 18,
    country: "Canada",
    flag: "🇨🇦",
    power: 68.7,
    budget: "22 Md$",
    forces: "67K",
  },
  {
    rank: 19,
    country: "Espagne",
    flag: "🇪🇸",
    power: 67.9,
    budget: "12 Md$",
    forces: "121K",
  },
  {
    rank: 20,
    country: "Arabie Saoudite",
    flag: "🇸🇦",
    power: 67.2,
    budget: "48 Md$",
    forces: "227K",
  },
  {
    rank: 21,
    country: "Indonésie",
    flag: "🇮🇩",
    power: 66.4,
    budget: "9 Md$",
    forces: "395K",
  },
  {
    rank: 22,
    country: "Pologne",
    flag: "🇵🇱",
    power: 65.8,
    budget: "12 Md$",
    forces: "114K",
  },
  {
    rank: 23,
    country: "Pays-Bas",
    flag: "🇳🇱",
    power: 65.1,
    budget: "13 Md$",
    forces: "37K",
  },
  {
    rank: 24,
    country: "Ukraine",
    flag: "🇺🇦",
    power: 64.5,
    budget: "6 Md$",
    forces: "209K",
  },
  {
    rank: 25,
    country: "Thaïlande",
    flag: "🇹🇭",
    power: 63.7,
    budget: "7 Md$",
    forces: "361K",
  },
  {
    rank: 26,
    country: "Taïwan",
    flag: "🇹🇼",
    power: 63.2,
    budget: "12 Md$",
    forces: "165K",
  },
  {
    rank: 27,
    country: "Algérie",
    flag: "🇩🇿",
    power: 62.6,
    budget: "9 Md$",
    forces: "130K",
  },
  {
    rank: 28,
    country: "Norvège",
    flag: "🇳🇴",
    power: 62.1,
    budget: "7 Md$",
    forces: "23K",
  },
  {
    rank: 29,
    country: "Suède",
    flag: "🇸🇪",
    power: 61.4,
    budget: "6 Md$",
    forces: "24K",
  },
  {
    rank: 30,
    country: "Grèce",
    flag: "🇬🇷",
    power: 60.8,
    budget: "5 Md$",
    forces: "142K",
  },
  {
    rank: 31,
    country: "Irak",
    flag: "🇮🇶",
    power: 60.2,
    budget: "5 Md$",
    forces: "193K",
  },
  {
    rank: 32,
    country: "Mexique",
    flag: "🇲🇽",
    power: 59.5,
    budget: "7 Md$",
    forces: "277K",
  },
  {
    rank: 33,
    country: "Finlande",
    flag: "🇫🇮",
    power: 58.9,
    budget: "5 Md$",
    forces: "22K",
  },
  {
    rank: 34,
    country: "Singapour",
    flag: "🇸🇬",
    power: 58.3,
    budget: "11 Md$",
    forces: "51K",
  },
  {
    rank: 35,
    country: "Chili",
    flag: "🇨🇱",
    power: 57.7,
    budget: "5 Md$",
    forces: "77K",
  },
  {
    rank: 36,
    country: "Bangladesh",
    flag: "🇧🇩",
    power: 57.1,
    budget: "4 Md$",
    forces: "157K",
  },
  {
    rank: 37,
    country: "Belgique",
    flag: "🇧🇪",
    power: 56.5,
    budget: "4 Md$",
    forces: "25K",
  },
  {
    rank: 38,
    country: "Suisse",
    flag: "🇨🇭",
    power: 55.9,
    budget: "5 Md$",
    forces: "21K",
  },
  {
    rank: 39,
    country: "Maroc",
    flag: "🇲🇦",
    power: 55.3,
    budget: "4 Md$",
    forces: "195K",
  },
  {
    rank: 40,
    country: "Colombie",
    flag: "🇨🇴",
    power: 54.7,
    budget: "10 Md$",
    forces: "293K",
  },
  {
    rank: 41,
    country: "Argentine",
    flag: "🇦🇷",
    power: 54.1,
    budget: "3 Md$",
    forces: "74K",
  },
  {
    rank: 42,
    country: "Pérou",
    flag: "🇵🇪",
    power: 53.5,
    budget: "3 Md$",
    forces: "81K",
  },
  {
    rank: 43,
    country: "Danemark",
    flag: "🇩🇰",
    power: 52.9,
    budget: "4 Md$",
    forces: "16K",
  },
  {
    rank: 44,
    country: "Portugal",
    flag: "🇵🇹",
    power: 52.3,
    budget: "3 Md$",
    forces: "27K",
  },
  {
    rank: 45,
    country: "République Tchèque",
    flag: "🇨🇿",
    power: 51.7,
    budget: "3 Md$",
    forces: "26K",
  },
  {
    rank: 46,
    country: "Roumanie",
    flag: "🇷🇴",
    power: 51.1,
    budget: "5 Md$",
    forces: "70K",
  },
  {
    rank: 47,
    country: "Autriche",
    flag: "🇦🇹",
    power: 50.5,
    budget: "3 Md$",
    forces: "22K",
  },
  {
    rank: 48,
    country: "Hongrie",
    flag: "🇭🇺",
    power: 49.9,
    budget: "3 Md$",
    forces: "23K",
  },
  {
    rank: 49,
    country: "Philippines",
    flag: "🇵🇭",
    power: 49.3,
    budget: "4 Md$",
    forces: "125K",
  },
  {
    rank: 50,
    country: "Vietnam",
    flag: "🇻🇳",
    power: 48.7,
    budget: "5 Md$",
    forces: "482K",
  },
];

const economicRankings = [
  {
    rank: 1,
    country: "États-Unis",
    flag: "🇺🇸",
    gdp: "23.3 T$",
    growth: "+2.1%",
    trade: "4.9 T$",
  },
  {
    rank: 2,
    country: "Chine",
    flag: "🇨🇳",
    gdp: "17.7 T$",
    growth: "+8.1%",
    trade: "4.6 T$",
  },
  {
    rank: 3,
    country: "Japon",
    flag: "🇯🇵",
    gdp: "4.9 T$",
    growth: "+1.6%",
    trade: "1.4 T$",
  },
  {
    rank: 4,
    country: "Allemagne",
    flag: "🇩🇪",
    gdp: "4.2 T$",
    growth: "+2.9%",
    trade: "3.6 T$",
  },
  {
    rank: 5,
    country: "Inde",
    flag: "🇮🇳",
    gdp: "3.7 T$",
    growth: "+6.1%",
    trade: "0.8 T$",
  },
  {
    rank: 6,
    country: "Royaume-Uni",
    flag: "🇬🇧",
    gdp: "3.1 T$",
    growth: "+7.5%",
    trade: "1.4 T$",
  },
  {
    rank: 7,
    country: "France",
    flag: "🇫🇷",
    gdp: "2.9 T$",
    growth: "+7.0%",
    trade: "1.3 T$",
  },
  {
    rank: 8,
    country: "Italie",
    flag: "🇮🇹",
    gdp: "2.1 T$",
    growth: "+6.6%",
    trade: "1.1 T$",
  },
  {
    rank: 9,
    country: "Brésil",
    flag: "🇧🇷",
    gdp: "1.9 T$",
    growth: "+4.6%",
    trade: "0.5 T$",
  },
  {
    rank: 10,
    country: "Canada",
    flag: "🇨🇦",
    gdp: "1.8 T$",
    growth: "+4.6%",
    trade: "0.9 T$",
  },
  {
    rank: 11,
    country: "Russie",
    flag: "🇷🇺",
    gdp: "1.8 T$",
    growth: "+4.7%",
    trade: "0.7 T$",
  },
  {
    rank: 12,
    country: "Corée du Sud",
    flag: "🇰🇷",
    gdp: "1.8 T$",
    growth: "+2.6%",
    trade: "1.2 T$",
  },
  {
    rank: 13,
    country: "Espagne",
    flag: "🇪🇸",
    gdp: "1.4 T$",
    growth: "+5.1%",
    trade: "0.8 T$",
  },
  {
    rank: 14,
    country: "Australie",
    flag: "🇦🇺",
    gdp: "1.4 T$",
    growth: "+4.2%",
    trade: "0.5 T$",
  },
  {
    rank: 15,
    country: "Mexique",
    flag: "🇲🇽",
    gdp: "1.3 T$",
    growth: "+3.1%",
    trade: "0.9 T$",
  },
  {
    rank: 16,
    country: "Indonésie",
    flag: "🇮🇩",
    gdp: "1.3 T$",
    growth: "+5.0%",
    trade: "0.4 T$",
  },
  {
    rank: 17,
    country: "Pays-Bas",
    flag: "🇳🇱",
    gdp: "0.9 T$",
    growth: "+2.8%",
    trade: "1.4 T$",
  },
  {
    rank: 18,
    country: "Arabie Saoudite",
    flag: "🇸🇦",
    gdp: "0.8 T$",
    growth: "+3.2%",
    trade: "0.5 T$",
  },
  {
    rank: 19,
    country: "Turquie",
    flag: "🇹🇷",
    gdp: "0.8 T$",
    growth: "+1.8%",
    trade: "0.4 T$",
  },
  {
    rank: 20,
    country: "Taïwan",
    flag: "🇹🇼",
    gdp: "0.8 T$",
    growth: "+3.1%",
    trade: "0.8 T$",
  },
  {
    rank: 21,
    country: "Suisse",
    flag: "🇨🇭",
    gdp: "0.8 T$",
    growth: "+3.7%",
    trade: "0.7 T$",
  },
  {
    rank: 22,
    country: "Belgique",
    flag: "🇧🇪",
    gdp: "0.5 T$",
    growth: "+6.1%",
    trade: "0.9 T$",
  },
  {
    rank: 23,
    country: "Argentine",
    flag: "🇦🇷",
    gdp: "0.5 T$",
    growth: "+10.3%",
    trade: "0.1 T$",
  },
  {
    rank: 24,
    country: "Irlande",
    flag: "🇮🇪",
    gdp: "0.5 T$",
    growth: "+13.5%",
    trade: "0.5 T$",
  },
  {
    rank: 25,
    country: "Israël",
    flag: "🇮🇱",
    gdp: "0.5 T$",
    growth: "+8.2%",
    trade: "0.2 T$",
  },
  {
    rank: 26,
    country: "Thaïlande",
    flag: "🇹🇭",
    gdp: "0.5 T$",
    growth: "+1.6%",
    trade: "0.5 T$",
  },
  {
    rank: 27,
    country: "Pologne",
    flag: "🇵🇱",
    gdp: "0.7 T$",
    growth: "+5.7%",
    trade: "0.6 T$",
  },
  {
    rank: 28,
    country: "Nigeria",
    flag: "🇳🇬",
    gdp: "0.4 T$",
    growth: "+2.7%",
    trade: "0.1 T$",
  },
  {
    rank: 29,
    country: "Égypte",
    flag: "🇪🇬",
    gdp: "0.4 T$",
    growth: "+3.3%",
    trade: "0.1 T$",
  },
  {
    rank: 30,
    country: "Autriche",
    flag: "🇦🇹",
    gdp: "0.4 T$",
    growth: "+4.8%",
    trade: "0.4 T$",
  },
  {
    rank: 31,
    country: "Norvège",
    flag: "🇳🇴",
    gdp: "0.4 T$",
    growth: "+3.9%",
    trade: "0.3 T$",
  },
  {
    rank: 32,
    country: "Afrique du Sud",
    flag: "🇿🇦",
    gdp: "0.4 T$",
    growth: "+4.9%",
    trade: "0.2 T$",
  },
  {
    rank: 33,
    country: "Philippines",
    flag: "🇵🇭",
    gdp: "0.4 T$",
    growth: "+5.6%",
    trade: "0.2 T$",
  },
  {
    rank: 34,
    country: "Bangladesh",
    flag: "🇧🇩",
    gdp: "0.4 T$",
    growth: "+6.9%",
    trade: "0.1 T$",
  },
  {
    rank: 35,
    country: "Vietnam",
    flag: "🇻🇳",
    gdp: "0.4 T$",
    growth: "+2.6%",
    trade: "0.6 T$",
  },
  {
    rank: 36,
    country: "Chili",
    flag: "🇨🇱",
    gdp: "0.3 T$",
    growth: "+11.7%",
    trade: "0.2 T$",
  },
  {
    rank: 37,
    country: "Finlande",
    flag: "🇫🇮",
    gdp: "0.3 T$",
    growth: "+3.0%",
    trade: "0.2 T$",
  },
  {
    rank: 38,
    country: "Roumanie",
    flag: "🇷🇴",
    gdp: "0.2 T$",
    growth: "+5.9%",
    trade: "0.2 T$",
  },
  {
    rank: 39,
    country: "République Tchèque",
    flag: "🇨🇿",
    gdp: "0.3 T$",
    growth: "+3.3%",
    trade: "0.4 T$",
  },
  {
    rank: 40,
    country: "Nouvelle-Zélande",
    flag: "🇳🇿",
    gdp: "0.2 T$",
    growth: "+5.6%",
    trade: "0.1 T$",
  },
  {
    rank: 41,
    country: "Pérou",
    flag: "🇵🇪",
    gdp: "0.2 T$",
    growth: "+13.3%",
    trade: "0.1 T$",
  },
  {
    rank: 42,
    country: "Portugal",
    flag: "🇵🇹",
    gdp: "0.2 T$",
    growth: "+4.9%",
    trade: "0.2 T$",
  },
  {
    rank: 43,
    country: "Grèce",
    flag: "🇬🇷",
    gdp: "0.2 T$",
    growth: "+8.3%",
    trade: "0.1 T$",
  },
  {
    rank: 44,
    country: "Irak",
    flag: "🇮🇶",
    gdp: "0.2 T$",
    growth: "+7.4%",
    trade: "0.2 T$",
  },
  {
    rank: 45,
    country: "Algérie",
    flag: "🇩🇿",
    gdp: "0.2 T$",
    growth: "+3.2%",
    trade: "0.1 T$",
  },
  {
    rank: 46,
    country: "Kazakhstan",
    flag: "🇰🇿",
    gdp: "0.2 T$",
    growth: "+4.3%",
    trade: "0.1 T$",
  },
  {
    rank: 47,
    country: "Qatar",
    flag: "🇶🇦",
    gdp: "0.2 T$",
    growth: "+1.5%",
    trade: "0.2 T$",
  },
  {
    rank: 48,
    country: "Hongrie",
    flag: "🇭🇺",
    gdp: "0.2 T$",
    growth: "+7.1%",
    trade: "0.2 T$",
  },
  {
    rank: 49,
    country: "Koweït",
    flag: "🇰🇼",
    gdp: "0.1 T$",
    growth: "+1.3%",
    trade: "0.1 T$",
  },
  {
    rank: 50,
    country: "Maroc",
    flag: "🇲🇦",
    gdp: "0.1 T$",
    growth: "+7.4%",
    trade: "0.1 T$",
  },
];

const newsData = [
  {
    title: "Tension géopolitique en mer de Chine méridionale",
    content:
      "Les tensions entre plusieurs nations se sont intensifiées cette semaine suite à de nouveaux mouvements militaires dans la région. Les forces navales de plusieurs puissances mondiales ont été déployées pour surveiller la situation.",
    category: "International",
    date: "15 Mars 2077",
    imageUrl: null,
  },
  {
    title: "Nouvelle alliance économique entre l'Europe et l'Asie",
    content:
      "Un accord commercial majeur a été signé aujourd'hui, créant une zone de libre-échange entre plusieurs nations européennes et asiatiques. Cet accord devrait stimuler les échanges commerciaux de 40% dans les prochaines années.",
    category: "Économie",
    date: "14 Mars 2077",
    imageUrl: null,
  },
  {
    title: "Sommet diplomatique pour la paix mondiale",
    content:
      "Les dirigeants de 50 nations se réunissent cette semaine pour discuter des enjeux de sécurité internationale et des mesures de désarmement. Cette conférence historique pourrait redéfinir les relations internationales.",
    category: "Diplomatie",
    date: "13 Mars 2077",
    imageUrl: null,
  },
  {
    title: "Crise énergétique mondiale : nouvelles solutions",
    content:
      "Face à la pénurie énergétique globale, plusieurs pays annoncent des investissements massifs dans les énergies renouvelables. Des projets de coopération internationale sont en cours de négociation.",
    category: "Environnement",
    date: "12 Mars 2077",
    imageUrl: null,
  },
  {
    title: "Révolution technologique dans l'armement",
    content:
      "De nouvelles technologies de défense sont dévoilées par les principales puissances militaires. Ces innovations pourraient changer l'équilibre des forces mondiales dans les années à venir.",
    category: "Technologie",
    date: "11 Mars 2077",
    imageUrl: null,
  },
  {
    title: "Accord de désarmement nucléaire historique",
    content:
      "Après des mois de négociations, plusieurs puissances nucléaires s'engagent à réduire leur arsenal de 30% d'ici 2080. Cet accord marque une étape importante vers la dénucléarisation mondiale.",
    category: "International",
    date: "10 Mars 2077",
    imageUrl: null,
  },
];

async function main() {
  console.log("🌱 Début du seeding de la base de données...");

  // Nettoyer les données existantes
  await prisma.militaryRanking.deleteMany();
  await prisma.economicRanking.deleteMany();
  await prisma.news.deleteMany();
  await prisma.gameDate.deleteMany();

  // Insérer les classements militaires
  console.log("📊 Insertion des classements militaires...");
  for (const ranking of militaryRankings) {
    await prisma.militaryRanking.create({
      data: ranking,
    });
  }

  // Insérer les classements économiques
  console.log("💰 Insertion des classements économiques...");
  for (const ranking of economicRankings) {
    await prisma.economicRanking.create({
      data: ranking,
    });
  }

  // Insérer les actualités
  console.log("📰 Insertion des actualités...");
  for (const news of newsData) {
    await prisma.news.create({
      data: news,
    });
  }

  // Insérer la date du jeu
  console.log("📅 Insertion de la date du jeu...");
  await prisma.gameDate.create({
    data: {
      date: "15 Mars 2077",
      isActive: true,
    },
  });

  console.log("✅ Seeding terminé avec succès!");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error: unknown) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
